# Generated by Django 2.2.6 on 2019-11-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamefitnessweb', '0002_auto_20191106_2035'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercises',
            table='exercises',
        ),
        migrations.AlterModelTable(
            name='games',
            table='games',
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
