# Generated by Django 2.2.7 on 2019-11-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefitnessweb', '0003_auto_20191107_0059'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_of_percieved_exertion', models.CharField(choices=[('0', '0 = no activity'), ('1', '1 = very easy'), ('2', '2 = easy'), ('3', '3 = moderate'), ('4', '4 = somewhat hard'), ('5', '5 = hard'), ('6', '6 = very hard'), ('7', '7 = maximal')], max_length=50)),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
