# Generated by Django 2.2.6 on 2019-12-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamefitnessweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='game_description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
